# Generated by Django 5.1.1 on 2024-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('icon', models.CharField(default='bi bi-file-earmark', max_length=200)),
                ('visibility', models.CharField(default='show', max_length=100)),
            ],
        ),
    ]
