# Generated by Django 5.1.1 on 2024-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='success', max_length=200)),
            ],
        ),
    ]
