# Generated by Django 5.1.1 on 2024-10-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0003_datafortablemodel_category_sidebarmenumodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmenumodel',
            name='relativepath',
            field=models.CharField(default='Home/Server', max_length=250),
        ),
    ]
