# Generated by Django 5.1.1 on 2024-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0004_sidebarmenumodel_relativepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmenumodel',
            name='pagename',
            field=models.CharField(default='empty.html', max_length=250),
        ),
    ]
