# Generated by Django 5.1.1 on 2024-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0005_sidebarmenumodel_pagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmenumodel',
            name='pagename',
            field=models.CharField(default='pages/empty.html', max_length=250),
        ),
    ]
