# Generated by Django 5.1.1 on 2024-10-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0006_alter_sidebarmenumodel_pagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafortablemodel',
            old_name='title',
            new_name='heading',
        ),
    ]
