# Generated by Django 5.1.1 on 2024-10-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0007_rename_title_datafortablemodel_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafortablemodel',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
