# Generated by Django 5.1.1 on 2024-10-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0008_datafortablemodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafortablemodel',
            name='heading',
        ),
        migrations.AlterField(
            model_name='datafortablemodel',
            name='title',
            field=models.CharField(default='Default Title', max_length=250),
        ),
    ]
