# Generated by Django 5.1.1 on 2024-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0009_remove_datafortablemodel_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmenumodel',
            name='table_title',
            field=models.CharField(default='Default Table Title', max_length=200),
        ),
    ]
